//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrotech_Management_System_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_Agrotech_Mgt_SystemEntities : DbContext
    {
        public DB_Agrotech_Mgt_SystemEntities()
            : base("name=DB_Agrotech_Mgt_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact_Details> Contact_Details { get; set; }
        public virtual DbSet<Login_Details> Login_Details { get; set; }
        public virtual DbSet<Payment_Details> Payment_Details { get; set; }
        public virtual DbSet<Product_Details> Product_Details { get; set; }
        public virtual DbSet<Register_Details> Register_Details { get; set; }
    
        public virtual ObjectResult<Sp_Insert_Contact_Result> Sp_Insert_Contact()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Insert_Contact_Result>("Sp_Insert_Contact");
        }
    
        public virtual ObjectResult<Sp_Insert_Login_Result> Sp_Insert_Login(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Insert_Login_Result>("Sp_Insert_Login", userParameter, passParameter);
        }
    
        public virtual ObjectResult<Sp_Insert_Payment_Result> Sp_Insert_Payment(Nullable<int> p1, Nullable<int> p2)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(int));
    
            var p2Parameter = p2.HasValue ?
                new ObjectParameter("p2", p2) :
                new ObjectParameter("p2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Insert_Payment_Result>("Sp_Insert_Payment", p1Parameter, p2Parameter);
        }
    
        public virtual ObjectResult<Sp_Insert_Product_Result> Sp_Insert_Product(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Insert_Product_Result>("Sp_Insert_Product", nameParameter);
        }
    
        public virtual ObjectResult<Sp_Insert_Register_Result> Sp_Insert_Register(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Insert_Register_Result>("Sp_Insert_Register", userParameter, passParameter);
        }
    }
}
