//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrotech_Management_System_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Details
    {
        public int Contact_ID { get; set; }
        public string Name { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string Message { get; set; }
    }
}
